name: Lint Format

on:
  pull_request:
    branches: [main]

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}

permissions:
  actions: write
  checks: write
  contents: write
  # deployments: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  lint:
    runs-on: self-hosted
    steps:
    - run: cat $GITHUB_EVENT_PATH
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Node.js dependencies
      run: yarn
    - name: Install Ruby Gem dependencies
      run: bundle
    - name: Lint
      run: bundle exec danger --dangerfile=scripts/ci_lint.rb --remove-previous-comments --verbose
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
